import { FormikProps } from "formik";
import { ISaveDataResponse } from "@ptypes/requestsInProgress/saveData/ISaveDataResponse";
import { IFormEntry } from "@ptypes/assignments/assignmentForm/IFormEntry";
import { IRequestSteps } from "@ptypes/feedback/requestProcess/IRequestSteps";
import { IAssistedStep } from "@inubekit/inubekit";
import { IFormAddPosition } from "../IFormAddPosition";
import { IOptionInitialiceEntry } from "../IOptionInitialiceEntry";

import { IGeneralInformationEntry } from "../IGeneralInformationEntry";
import { IModalData } from "@ptypes/users/tabs/userTab/addUser/IModalData";
interface IAddPositionUI {
  currentStep: number;
  generalInformationRef: React.RefObject<FormikProps<IGeneralInformationEntry> | null>;
  initialValues: IFormAddPosition;
  isCurrentFormValid: boolean;
  steps: IAssistedStep[];
  onNextStep: () => void;
  onPreviousStep: () => void;
  onToggleModal: () => void;
  onToggleApplicationStatus: () => void;
  setIsCurrentFormValid: React.Dispatch<React.SetStateAction<boolean>>;
  selectedToggle: IFormEntry[];
  setCurrentStep: (step: number) => void;
  setSelectedToggle: React.Dispatch<React.SetStateAction<IFormEntry[]>>;
  handlePreviousStep: () => void;
  handleNextStep: () => void;
  formValues: IFormAddPosition;
  smallScreen: boolean;
  disabled: boolean;
  roles: IFormEntry[];
  onFinishForm: () => void;
  showModal: boolean;
  showModalApplicationStatus: boolean;
  savePositions: ISaveDataResponse;
  showRequestProcessModal: boolean;
  showPendingReqModal: boolean;
  loading: boolean;
  navigate: (path: string) => void;
  onCloseRequestStatus: () => void;
  showMultipurposeModal: boolean;
  setShowMultipurposeModal: React.Dispatch<React.SetStateAction<boolean>>;
  onClosePendingReqModal: () => void;
  options: IOptionInitialiceEntry[];
  requestSteps: IRequestSteps[];
  modalData: IModalData;
  showDecision: boolean;
  onCloseProcess: () => void;
}

export type { IAddPositionUI };
