import { IAssistedSize, IAssistedStep } from "@inubekit/inubekit";
import { IFormsAddUserGeneralFormRefs } from "../forms/IGeneralFormValues/ref";
import { IGeneralUserFormValues } from "../forms/IGeneralFormValues";
import { IFormEntry } from "@ptypes/assignments/assignmentForm/IFormEntry";
import React, { Dispatch, SetStateAction } from "react";
import { IPositionByBusinessUnit } from "../forms/ByBusinessUnit/IPositionByBusinessUnit";
import { ISaveDataResponse } from "@src/types/saveData/ISaveDataResponse";
import { IRequestSteps } from "@src/types/requestsInProgress/IRequestSteps";

interface IAddUserUI {
  showGoBackModal: boolean;
  smallScreen: boolean;
  showMissionNameModal: boolean;
  title: string;
  description?: string;
  handleModal: () => void;
  steps: IAssistedStep[];
  currentStep: number;
  isCurrentFormValid: boolean;
  onNextStep: () => void;
  onPreviousStep: () => void;
  setIsCurrentFormValid: React.Dispatch<React.SetStateAction<boolean>>;
  formReferences: IFormsAddUserGeneralFormRefs;
  initialValues: IGeneralUserFormValues;
  onGoBack: () => void;
  assistedLength: IAssistedSize;
  onToggleModal: () => void;
  onToggleMissionModal: () => void;
  setEntriesAdditionalBusinessEntity: Dispatch<SetStateAction<IFormEntry[]>>;
  entriesAdditionalBusinessEntity: IFormEntry[];
  positionsByBusinessUnit: Record<string, IPositionByBusinessUnit>;
  selectPositionsByBusinessUnit: (name: string, value: string) => void;
  rolesByBusinessUnit: IFormEntry[];
  saveUsers: ISaveDataResponse;
  requestSteps: IRequestSteps[];
  showPendingReqModal: boolean;
  showRequestProcessModal: boolean;
  showModal: boolean;
  onCloseRequestStatus: () => void;
  onCloseProcess: () => void;
  onClosePendingReqModal: () => void;
  selectRolesByBusinessUnit: Dispatch<SetStateAction<IFormEntry[]>>;
  onSubmit: () => void;
}
export type { IAddUserUI };
